/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_propheta13_amoduse_IoctlWrapper */

#ifndef _Included_com_propheta13_amoduse_IoctlWrapper
#define _Included_com_propheta13_amoduse_IoctlWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_propheta13_amoduse_IoctlWrapper
 * Method:    getKData
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_propheta13_amoduse_IoctlWrapper_getKData
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
